syntax = "proto3";
option java_package = "de.klabz.karootilehunting.data";
option java_multiple_files = true;

message Tile {
  int32 x = 1;
  int32 y = 2;
}

message ExploredTiles {
  repeated Tile exploredTiles = 1;
  repeated Tile recentlyExploredTiles = 2;
  repeated Tile recentlyExploredNewTiles = 3;

  uint64 lastDownloadedAt = 4;
  bool isDownloading = 5;
  uint32 downloadedActivities = 6;
  string lastDownloadError = 7;

  uint32 biggestSquareX = 8;
  uint32 biggestSquareY = 9;
  uint32 biggestSquareSize = 10;
}
